services:
  front:
    build:
      context: ./next
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - type: volume
        source: node_modules
        target: /app/next/node_modules
        volume:
          nocopy: false
    environment:
      - NODE_ENV=development
    tty: true
    working_dir: /app/next
    command: npm run dev

volumes:
  node_modules:
